all: verifyMult_0 verifyMult_1 verifyMult_2

verifyMult_0:
	@cp -f datasets/data_0_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl 
verifyMult_1:
	@cp -f datasets/data_1_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl

verifyMult_2:
	@cp -f datasets/data_2_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl

verifyMult_5:
	@cp -f datasets/data_5_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl 
verifyMult_6:
	@cp -f datasets/data_6_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl

verifyMult_7:
	@cp -f datasets/data_7_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl

verifyMult_8:
	@cp -f datasets/data_7_11_22_1k/* datasets/tmp
	@maple maple_operation_mult_revised_high_level.mpl
